### ISSUE TITLE
OER saves students $100M: Infographic

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/stateofthe#23]
It is unclear whether the number is US-specific or global. Maybe this information could be added to the FB/twitter box or to the full report. Currently I can't find additional description about this part e.g. when, where, and how we got this number whereas other parts are covered in more detail in the report.

**Comment by mattl** [comment]
Hoping Cable has some insight.

**Comment by cablegreen** [comment]
This is a global number - though it is low and outdated.  It comes from this 2013 Open Educational Resources conference presentation: http://www.slideshare.net/txtbks/billion-dollar-keynote
