### ISSUE TITLE
methodology explanations

### ISSUE THREAD

**Issue by mlinksva** [creativecommons/stateofthe#26]
Hi, great report. I have some questions that I suppose could be "issues" in that it would be nice if the answers were obvious in data/notes.md.

* Is the cumulative number of licensed works the sum of the platform counts and google data files? It seems like that must be the case, but would be nice to say.
* What are google data files?
* How are the free/nonfree breakdowns arrived at, for 2014 and 2010? It is great to see such a shift in the direction of free licenses!
* ~~How is the geographic breakdown arrived at?~~ (oops, I see data/notes.md says web stats for license chooser)

**Comment by mattl** [comment]
Closing this issue, I don't know if we'll get answers to this.
