### ISSUE TITLE
review data ask re license urls

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/stateofthe#31]
@mattl could you review this [doc](https://docs.google.com/document/d/1IVXICk3KMdLBgIiGZ49Bgz_dehjK6Rh5XTZIKg1Bw3Q/edit) (only open to cc staff) ASAP to make sure it is up to date regarding data we are asking for SOTC? thank you!

**Comment by robmyers** [comment]
I took a look. I can't see any anything missing that we'd want data on.
