### ISSUE TITLE
How do we determine which CC platforms are not cached by Google? 

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/stateofthe#33]
Hey @robmyers, could use some help. Do you know how we arrived at this list of platforms last year? https://github.com/creativecommons/stateofthe/blob/master/data/notes.md#number-of-creative-commons--licensed-works

Is it as simple as looking at platforms to see if they have not enabled CC license links to each page/piece of content, or something else?

**Comment by mattl** [comment]
They were just platforms we knew had a lot of works, I think.

**Comment by janeatcc** [comment]
But how do we know they were not cached by Google?

**Comment by mattl** [comment]
For example:

We ask Flickr how many CC licensed images they have.

We look at the results Google give us to see how many times Flickr appears
in there.

**Comment by janeatcc** [comment]
The Google data from last year doesn't have reference to Flickr or any other websites, just gives us total # per license deed/version: https://github.com/creativecommons/stateofthe/blob/master/data/notes.md#google-data-files

Sorry if I'm missing something.

**Comment by mattl** [comment]
Maybe I'm misremembering, but I think there was more data from Google and
Bing that wasn't published that we were using for this kind of thing.

If we can't find it, I can see if it's Elliot's old emails on Tuesday.

**Comment by janeatcc** [comment]
Ok, thank you! I've also pinged Elliot.

**Comment by janeatcc** [comment]
@mattl haven't heard back from elliot. do you think you could see if we have more raw data files from google last year where we got that number? thanks!

**Comment by mattl** [comment]
I'll take a look in Elliot's emails and see if I can find them

**Comment by janeatcc** [comment]
Just checking on this!
