### ISSUE TITLE
DeviantArt license metadata call via API

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/stateofthe#34]
How to get by license via metadata call? https://www.deviantart.com/developers/http/v1/20151014/deviation_metadata/7824fc14d6fba6acbacca1cf38c24158

Last data cited from this post: https://creativecommons.org/weblog/entry/35540 (15 million artworks)

**Comment by robmyers** [comment]
Ah I misunderstood the question, sorry. Yes I think we'll need to get the stats from source.
