### ISSUE TITLE
Total CC items on Libre.fm

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/stateofthe#35]
Please note total # plus source (link and/or methodology).

**Comment by janeatcc** [comment]
Possible to get by EOD Wed 11 November?

**Comment by janeatcc** [comment]
Need this today!

**Comment by mattl** [comment]
133464366

**Comment by janeatcc** [comment]
Thank you! Source and/or link?

**Comment by mattl** [comment]
https://librefm.wordpress.com/2015/11/13/133-million-songs-and-counting/

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by janeatcc** [comment]
Yas
