### ISSUE TITLE
Total CC items via GNU Social

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/stateofthe#36]
Please note total # plus source (link and/or methodology).

**Comment by janeatcc** [comment]
Possible to get by EOD Wed 11 November?

**Comment by janeatcc** [comment]
Need this today! Can we get it?

**Comment by mattl** [comment]
Sadly, I don't have a good source for this number.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by janeatcc** [comment]
Ok. I don't think we need it.
