### ISSUE TITLE
Push complete English version to web (in private mode until 12/8)

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/stateofthe#37]
Also create a separate page for data sources and give Jane edit capabilities so she can add later. 

Will ping again once we have final. This can happen on Monday, right @rebeccalendl?

Note, please keep web pages private until 12/8.

**Comment by rebeccalendl** [comment]
@mattl you should have everything we have, let us know if you need anything additional. and let us know when these pages (full version / condensed version) are live and private. we can use to share out as a 'sneak preview' for key supporters.

**Comment by mattl** [comment]
I don't have the final SVG files. If you could email those, that'd be great.

**Comment by rebeccalendl** [comment]
should be in that folder. resending invite.

**Comment by mattl** [comment]
Weirdly i'm not seeing the invite, but I see them in Google Drive now. 

The condensed version is the one that's being translated, right?

**Comment by rebeccalendl** [comment]
Yes. And just to clarify, we'll want the full version (not condensed) to be our 'main version' that all other comms point too.
